#define TITLE "Bomba Invaders"

#define WINDOW_WIDTH 750
#define WINDOW_HEIGHT 700

#define GREY (Color){29, 29, 27, 255}

#define FPS 60

#define SPACESHIP_SPEED 5

#define LASER_WIDTH 5
#define LASER_HEIGHT 15
#define LASER_SPEED 5
#define LASER_FIRE_DELAY 0.15

#define ALIEN_ROWS 5
#define ALIEN_COLS 11
#define ALIEN_SIZE 55
#define ALIENS_MOVE_DOWN_DISTANCE 5
#define ALIEN_SPEED 1
#define ALIEN_SHOOT_INTERVAL 0.35

#define MYSTERYSHIP_SPEED 2
#define MYSTERYSHIP_MIN_SPAWN_TIME 10
#define MYSTERYSHIP_MAX_SPAWN_TIME 20
#define MYSTERYSHIP_SPAWN_TIME_DELAY 7

#define UI_OFFSET 50